### ISSUE TITLE
How to make BindingPropertyAttribute effective on ObservableList<>

### ISSUE THREAD

**Issue by eefan000** [Zitga-Tech/ZBase.Foundation.Mvvm#7]
It seems to have failed in UnionConverter. As it was generated by code, I don't know how to debug breakpoints and cannot determine the specific location of the failure

**Comment by eefan000** [comment]
![image](https://github.com/user-attachments/assets/796cd50b-bad4-4a83-ab97-3135a8084066)
Inconsistent TypeId

**Comment by eefan000** [comment]
It seems that a converter needs to be implemented

**Comment by grashaar** [comment]
Hi @eefan000, I would like to inform you that I'm no longer be able to make any big contribution to this package (and Zitga Tech as a whole) since I've moved out of the company recently. In the future you might see this package in another form, by another name. But for the time being, I'm going to spend time on some personal stuffs.

Regarding ObservableList and the likes, I'd feel very appreciated if you could spend some time investigating if [Cysharp/ObservableCollections](https://github.com/Cysharp/ObservableCollections) can work with this MVVM implementation? Because I would like to not reinvent the wheel if possible. If push comes to shove, I would like to just copy the code of Cysharp/ObservableCollections and do little modifications.

**Comment by eefan000** [comment]
> Hi @eefan000, I would like to inform you that I'm no longer be able to make any big contribution to this package (and Zitga Tech as a whole) since I've moved out of the company recently. In the future you might see this package in another form, by another name. But for the time being, I'm going to spend time on some personal stuffs.
> 
> Regarding ObservableList and the likes, I'd feel very appreciated if you could spend some time investigating if [Cysharp/ObservableCollections](https://github.com/Cysharp/ObservableCollections) can work with this MVVM implementation? Because I would like to not reinvent the wheel if possible. If push comes to shove, I would like to just copy the code of Cysharp/ObservableCollections and do little modifications.

@grashaar 
It should be seamless to use. I have now implemented a simple infinite list data binding that can be directly used with any container. I use ObservableList<>just because it happens to be available.

Looking forward to your new library！
If it comes out, please let me know！

![image](https://github.com/user-attachments/assets/c5ddb0a8-97a8-4693-a293-321c559af3d0)
![image](https://github.com/user-attachments/assets/3ebaed58-4052-4dbc-be40-d1f4470e0b22)
![image](https://github.com/user-attachments/assets/3ced9acf-556b-492e-8e5d-663e9280a42f)
![image](https://github.com/user-attachments/assets/9cd8ef01-0e57-448b-9aea-7087384a3611)
![image](https://github.com/user-attachments/assets/adb84494-24d8-4c77-9f4f-4af263a3634e)
![image](https://github.com/user-attachments/assets/04b6bf24-acf2-4b41-8071-ef6a6b033bc6)

**Comment by grashaar** [comment]
It's good to know that this approach work for you seemlessly.
